# Generated by Django 5.1.3 on 2024-11-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0003_aaluno_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='profissao',
            field=models.CharField(choices=[('coordenador', 'Coordenador'), ('colaborador', 'Colaborador')], max_length=50),
        ),
    ]
