# Generated by Django 5.1.3 on 2024-11-21 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0004_alter_cadastro_profissao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acurso',
            options={'permissions': [('can_edit_courses', 'Pode editar cursos'), ('can_delete_courses', 'Pode excluir cursos')]},
        ),
    ]
