# Generated by Django 5.1.3 on 2024-11-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0005_alter_acurso_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acurso',
            options={'permissions': [('can_add_courses', 'Pode adicionar cursos'), ('can_edit_courses', 'Pode editar cursos'), ('can_delete_courses', 'Pode excluir cursos')]},
        ),
    ]
