# Generated by Django 5.1.3 on 2024-11-26 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0006_alter_acurso_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aaluno',
            options={'permissions': [('can_add_alunos', 'Pode adicionar alunos'), ('can_edit_alunos', 'Pode editar alunos'), ('can_delte_alunoss', 'Pode excluir alunos')]},
        ),
        migrations.AlterModelOptions(
            name='acurso',
            options={'permissions': [('can_add_courses', 'Pode adicionar cursos'), ('can_edit_courses', 'Pode editar cursos'), ('can_delete_courses', 'Pode excluir cursos')], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='aturma',
            options={'permissions': [('can_add_turmas', 'Pode adicionar turmas'), ('can_edit_turmas', 'Pode editar turmas'), ('can_delte_turmas', 'Pode excluir turmas')]},
        ),
        migrations.AlterModelOptions(
            name='cadastro',
            options={'permissions': [('can_add_cadastro', 'Pode adicionar alunos')]},
        ),
        migrations.RemoveField(
            model_name='acurso',
            name='icon',
        ),
    ]
