# Generated by Django 5.1.3 on 2024-12-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0007_alter_aaluno_options_alter_acurso_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aaluno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_alunos/'),
        ),
    ]
